# Generated by Django 5.2.13 on 2026-05-01 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('esta_id', models.IntegerField(primary_key=True, serialize=False)),
                ('esta_identificador', models.CharField(max_length=1)),
                ('esta_nombre', models.CharField(max_length=100)),
                ('esta_color', models.CharField(blank=True, max_length=7, null=True)),
                ('esta_uso', models.CharField(blank=True, choices=[('VR', 'Vaca - Reproductivo'), ('VP', 'Vaca - Productivo')], max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('pais_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pais_nombre', models.CharField(max_length=100)),
                ('pais_descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'pais',
                'ordering': ['pais_nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('tiun_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tiun_nombre', models.CharField(max_length=100)),
                ('tiun_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('tiun_descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Unidad',
                'verbose_name_plural': 'Tipos de Unidad',
                'db_table': 'tipo_unidad',
                'ordering': ['tiun_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('prvi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prvi_nombre', models.CharField(max_length=100)),
                ('prvi_descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provincias', to='catalogos.pais')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
                'ordering': ['prvi_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('loca_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loca_nombre', models.CharField(max_length=100)),
                ('loca_descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidades', to='catalogos.provincia')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidad',
                'ordering': ['loca_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('unid_id', models.IntegerField(primary_key=True, serialize=False)),
                ('unid_nombre', models.CharField(max_length=100)),
                ('unid_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('unid_descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='catalogos.tipounidad')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidad',
                'ordering': ['unid_nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConversionUnidad',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('coun_id', models.IntegerField(primary_key=True, serialize=False)),
                ('coun_proporcion', models.FloatField(blank=True, null=True)),
                ('coun_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('coun_descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversiones_destino', to='catalogos.unidad')),
                ('unidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversiones_origen', to='catalogos.unidad')),
            ],
            options={
                'verbose_name': 'Conversión de Unidad',
                'verbose_name_plural': 'Conversiones de Unidad',
                'db_table': 'conversion_unidad',
            },
        ),
    ]
