# Generated by Django 5.2.13 on 2026-05-01 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMovimiento',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('camo_id', models.AutoField(primary_key=True, serialize=False)),
                ('camo_nombre', models.CharField(max_length=100)),
                ('camo_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('camo_descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Movimiento',
                'verbose_name_plural': 'Categorías de Movimiento',
                'db_table': 'categoria_movimiento',
                'ordering': ['camo_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('caja_id', models.AutoField(primary_key=True, serialize=False)),
                ('caja_fecha_inicio', models.DateTimeField()),
                ('caja_fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('caja_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('caja_descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='gestion.establecimiento')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'caja',
                'ordering': ['-caja_fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('clie_id', models.AutoField(primary_key=True, serialize=False)),
                ('clie_nombre', models.CharField(max_length=100)),
                ('clie_imagen', models.BooleanField(default=False)),
                ('cuit', models.CharField(blank=True, max_length=13, null=True)),
                ('clie_direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('clie_codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('clie_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('clie_fax', models.CharField(blank=True, max_length=50, null=True)),
                ('clie_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('clie_contacto_nya', models.CharField(blank=True, max_length=100, null=True)),
                ('clie_contacto_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('clie_contacto_celular', models.CharField(blank=True, max_length=50, null=True)),
                ('clie_contacto_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('clie_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('clie_descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='catalogos.localidad')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['clie_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_fecha', models.DateTimeField()),
                ('comp_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('comp_descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='gestion.establecimiento')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
                'ordering': ['-comp_fecha'],
            },
        ),
        migrations.CreateModel(
            name='CompraAnimalDetalle',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cade_id', models.AutoField(primary_key=True, serialize=False)),
                ('cade_peso_compra', models.FloatField(blank=True, null=True)),
                ('cade_precio_compra', models.FloatField(blank=True, null=True)),
                ('cade_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_detalle', to='gestion.animal')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_animal', to='contabilidad.compra')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_animal', to='catalogos.unidad')),
            ],
            options={
                'verbose_name': 'Detalle Compra Animal',
                'db_table': 'compra_animal_detalle',
            },
        ),
        migrations.CreateModel(
            name='CompraCultivoDetalle',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ccde_id', models.AutoField(primary_key=True, serialize=False)),
                ('ccde_cantidad', models.FloatField(blank=True, null=True)),
                ('ccde_precio_compra', models.FloatField(blank=True, null=True)),
                ('ccde_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_cultivo', to='contabilidad.compra')),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.cultivo')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_cultivo', to='catalogos.unidad')),
            ],
            options={
                'verbose_name': 'Detalle Compra Cultivo',
                'db_table': 'compra_cultivo_detalle',
            },
        ),
        migrations.CreateModel(
            name='ConceptoMovimiento',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('como_id', models.AutoField(primary_key=True, serialize=False)),
                ('como_codigo', models.CharField(blank=True, max_length=5, null=True)),
                ('como_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('como_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('como_descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria_movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos', to='contabilidad.categoriamovimiento')),
            ],
            options={
                'verbose_name': 'Concepto de Movimiento',
                'verbose_name_plural': 'Conceptos de Movimiento',
                'db_table': 'concepto_movimiento',
                'ordering': ['como_nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('moca_id', models.AutoField(primary_key=True, serialize=False)),
                ('moca_fecha', models.DateTimeField()),
                ('moca_tipo', models.CharField(blank=True, choices=[('D', 'Debe'), ('H', 'Haber')], max_length=1, null=True)),
                ('moca_cantidad', models.FloatField(blank=True, null=True)),
                ('moca_monto', models.FloatField(blank=True, null=True)),
                ('moca_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('moca_descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.caja')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.conceptomovimiento')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='catalogos.unidad')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'db_table': 'movimiento_caja',
                'ordering': ['-moca_fecha'],
            },
        ),
        migrations.CreateModel(
            name='CompraMovimientoCaja',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('comc_id', models.AutoField(primary_key=True, serialize=False)),
                ('comc_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('comc_descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='contabilidad.compra')),
                ('movimiento_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.movimientocaja')),
            ],
            options={
                'verbose_name': 'Compra-Movimiento Caja',
                'db_table': 'compra_movimiento_caja',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('prov_id', models.AutoField(primary_key=True, serialize=False)),
                ('prov_nombre', models.CharField(max_length=100)),
                ('cuit', models.CharField(blank=True, max_length=13, null=True)),
                ('prov_direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('prov_codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('prov_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('prov_fax', models.CharField(blank=True, max_length=50, null=True)),
                ('prov_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('prov_contacto_nya', models.CharField(blank=True, max_length=100, null=True)),
                ('prov_contacto_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('prov_contacto_celular', models.CharField(blank=True, max_length=50, null=True)),
                ('prov_contacto_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('prov_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('prov_descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='catalogos.localidad')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['prov_nombre'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='contabilidad.proveedor'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('vent_id', models.AutoField(primary_key=True, serialize=False)),
                ('vent_fecha', models.DateTimeField()),
                ('vent_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('vent_descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='contabilidad.cliente')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='gestion.establecimiento')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['-vent_fecha'],
            },
        ),
        migrations.CreateModel(
            name='VentaAnimalDetalle',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('vade_id', models.AutoField(primary_key=True, serialize=False)),
                ('vade_peso_venta', models.FloatField(blank=True, null=True)),
                ('vade_precio_venta', models.FloatField(blank=True, null=True)),
                ('vade_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalle', to='gestion.animal')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_animal', to='catalogos.unidad')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_animal', to='contabilidad.venta')),
            ],
            options={
                'verbose_name': 'Detalle Venta Animal',
                'db_table': 'venta_animal_detalle',
            },
        ),
        migrations.CreateModel(
            name='VentaCosechaDetalle',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('vcde_id', models.AutoField(primary_key=True, serialize=False)),
                ('vcde_cantidad', models.FloatField(blank=True, null=True)),
                ('vcde_precio_venta', models.FloatField(blank=True, null=True)),
                ('vcde_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.cultivo')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_cosecha', to='catalogos.unidad')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_cosecha', to='contabilidad.venta')),
            ],
            options={
                'verbose_name': 'Detalle Venta Cosecha',
                'db_table': 'venta_cosecha_detalle',
            },
        ),
        migrations.CreateModel(
            name='VentaMovimientoCaja',
            fields=[
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('vemc_id', models.AutoField(primary_key=True, serialize=False)),
                ('vemc_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('vemc_descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('movimiento_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.movimientocaja')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='contabilidad.venta')),
            ],
            options={
                'verbose_name': 'Venta-Movimiento Caja',
                'db_table': 'venta_movimiento_caja',
            },
        ),
    ]
