# Generated by Django 5.2.13 on 2026-05-01 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, editable=False, null=True)),
                ('usua_id', models.AutoField(primary_key=True, serialize=False)),
                ('usua_nombre', models.CharField(max_length=50, unique=True)),
                ('usua_persona_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('usua_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('usua_observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
